[package]
name = "valor-lib"
description = "Plugin runtime as HTTP API running in server and browser"
license = "GPL-3.0-or-later"
version = "0.3.4"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/valor"

[dependencies]
http-types = "2.8.0"
path-tree = "0.1.12"
serde = { version = "1.0.117", default-features = false, features = ["alloc", "derive"] }
serde_json = "1.0.59"
valor-vlugin = { path = "./valor-vlugin", version = "0.3.0" }

[features]
native = []
web = []

[workspace]
default-members = ["valor-native"]
members = [
	"valor-native",
	"valor-web",
	"valor-vlugin",

	"examples/hello-plugin"
]

[profile.release.package.valor-web]
opt-level = "s"

[profile.release]
lto = true
